import { AnyEvent } from "@atrilabs/forest";
import { BrowserForestManager } from "./browserForestManager";
import { BrowserClient } from "./types";

/**
 * createAPI is responsible to keep BrowserForestManager & backend in sync.
 * This module will be part of frontend bundle.
 * @param client
 */
function createAPI(client: BrowserClient) {
  function postNewEvent(forestPkgId: string, pageId: string, event: AnyEvent) {
    const forest = BrowserForestManager.getForest(forestPkgId, pageId);
    if (forest) {
      forest.handleEvent(event);
      client.postNewEvent(forestPkgId, pageId, event, (success) => {
        if (!success) {
          console.log("Failed to send event to backend");
        }
      });
    }
  }
  return { ...client, postNewEvent };
}

/**
 * Following line will be generated by a babel-loader
 * import Client from "some-client";
 * And the declare statement below will be replaced with this import statement.
 */
declare var client: BrowserClient;

export default createAPI(client);
